---
- include: resolvconf.yml
  when: common_resolvconf
  tags: ['common', 'resolvconf']

- include: hostname.yml
  when: common_hostname
  tags: ['common', 'hostname']

- include: apt.yml
  when: common_apt
  tags: ['common', 'apt']

- include: locales.yml
  when: common_locales
  tags: ['common', 'locales']

- name: set vim as default editor
  alternatives: name=editor path=/usr/bin/vim.basic
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags: common

- name: copy some custom script
  copy: dest="{{ item.dest }}" src="{{ item.src }}" owner=root group=root mode=0755
  with_items: "{{ common_scripts }}"
  tags: common

- include: mailer.yml
  when: common_mailer
  tags: ['common', 'mailer']

- include: ntp.yml
  when: common_ntp
  tags: ['common', 'ntp']

- include: openssh.yml
  when: common_openssh
  tags: ['common', 'openssh']

- include: rsyslog.yml
  when: common_rsyslog
  tags: ['common', 'rsyslog']
