---

- name: ntp - install chrony
  apt: name=chrony
  when: ansible_virtualization_type != 'lxc' or ansible_virtualization_role == 'host'

- name: ntp - run and enable chrony
  service: name=chrony state=started enabled=yes
  when: ansible_virtualization_type != 'lxc' or ansible_virtualization_role == 'host'
