---

- name: install postfix
  apt: name="postfix" state=present

- name: postfix config
  template: dest="/etc/postfix/{{ item }}" src="postfix/{{ item }}.j2" owner=root group=root mode=0644
  with_items:
    - main.cf
    - master.cf
  notify: restart mailer

- name: postfix - start and enable
  service: name=postfix state=started enabled=yes
