---

- name: install postfix
  apt: name="postfix" state=present
  tags: ['common', 'postfix']

- name: postfix config
  template: dest="/etc/postfix/{{ item }}" src="postfix/{{ item }}.j2" owner=root group=root mode=0644
  with_items:
    - main.cf
    - master.cf
  notify: restart mailer
  tags: ['common', 'postfix']
