---
- name: resolvconf - remove
  apt: name=resolvconf state=absent
  when: common_resolvconf_remove_resolvconf

- name: /etc/resolv.conf
  template:
      dest: /etc/resolv.conf
      src: resolv.conf.j2
      owner: root
      group: root
      mode: 0644
  when: common_resolvconf_remove_resolvconf
