---

- name: restart ntp
  service: name=ntp state=restarted

- name: restart rsyslog
  service: name=rsyslog state=restarted

- name: reload openssh
  service: name=ssh state=reloaded

- name: restart openssh
  service: name=ssh state=restarted

- name: restart resolvconf
  service: name=resolvconf state=restarted

- name: reload mailer
  service: name="{{ common_mailer_mailer }}" state=reloaded

- name: restart mailer
  service: name="{{ common_mailer_mailer }}" state=restarted

- name: newaliases
  command: newaliases

- name: apt-get update
  apt: update_cache=yes
